# Generated by Django 3.1.7 on 2021-03-29 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers and special characters allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')])),
                ('Producer', models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers and special characters allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')])),
                ('Genre', models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers and special characters allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')])),
                ('Cast', models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers and special characters allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')])),
                ('Director', models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers and special characters allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')])),
                ('Year_of_production', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'unique_together': {('Title', 'Producer', 'Genre', 'Cast', 'Director', 'Year_of_production')},
            },
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_price', models.PositiveIntegerField()),
                ('Order_date', models.DateField(auto_now_add=True)),
                ('Ordered_Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapiii.movies')),
                ('Ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
