# Generated by Django 3.1.7 on 2021-03-27 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapiii', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Cast',
            field=models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers are not allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Director',
            field=models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers are not allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Genre',
            field=models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers are not allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Producer',
            field=models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers are not allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Title',
            field=models.CharField(help_text='Input should start with capital letter, separate entities by comma and space only,numbers are not allowed', max_length=200, validators=[django.core.validators.RegexValidator(message='Ensure this is a valid input corresponding to the field, check help text', regex='^[A-Z][\\w .,]+[a-zA-Z]$')]),
        ),
    ]
